name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install uv
        run: |
          pip install uv
      - name: Install dependencies with uv
        run: |
          uv pip install -r uv.lock --system
      - name: Install ruff
        run: |
          uv pip install ruff
      - name: Lint with ruff
        run: |
          ruff check msg tests
      - name: Run tests with pytest
        run: |
          pytest
